//
//  SearchCharactersPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharactersPresentationLogic {
    func presentSearchResults(response: SearchCharacters.Model.Response)
    func showLocalDefaultCharacters(response: SearchCharacters.Model.Response)
    func showError(with error: AppError)
}

class SearchCharactersPresenter: SearchCharactersPresentationLogic {
    weak var viewController: SearchCharactersDisplayLogic?
    
    func presentSearchResults(response: SearchCharacters.Model.Response) {
        let viewModel = SearchCharacters.Model.ViewModel(characters: response.characters)
        viewController?.displayData(viewModel: viewModel)
    }
    
    func showLocalDefaultCharacters(response: SearchCharacters.Model.Response) {
        let viewModel = SearchCharacters.Model.ViewModel(characters: response.characters)
        viewController?.displayData(viewModel: viewModel)
    }
    
    func showError(with error: AppError) {
        viewController?.showError(error: error)
    }
}
