//
//  BattleArenaRouter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BattleArenaRoutingLogic {
    func routeToSearchController()
}

protocol BattleArenaDataPassing {
    var dataStore: BattleArenaDataStore? { get }
}

class BattleArenaRouter: NSObject, BattleArenaRoutingLogic, BattleArenaDataPassing {
    weak var viewController: BattleArenaViewController?
    var dataStore: BattleArenaDataStore?
    
    func routeToSearchController() {
        guard let BattleArenaViewController = viewController else { return }
        let searchViewController = SearchCharactersViewController()
        searchViewController.isBattle = true
        BattleArenaViewController.show(searchViewController, sender: self)
    }
    
}
