//
//  RankingsPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsPresentationLogic {
    func presentRankings(response: Rankings.Model.Response)
    func showError(error: AppError)
}

class RankingsPresenter: RankingsPresentationLogic {
    weak var viewController: RankingsDisplayLogic?
    
    func presentRankings(response: Rankings.Model.Response) {
        let viewModel = Rankings.Model.ViewModel(rankings: response.rankings)
        viewController?.showRankings(viewModel: viewModel)
    }
    
    func showError(error: AppError) {
        viewController?.showError(with: error)
    }
}
