//
//  SearchCharactersInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharactersBusinessLogic {
    func searchCharacterNames(request: SearchCharacters.Model.Request)
    func searchAllCharacters()
}

protocol SearchCharactersDataStore {
}

class SearchCharactersInteractor: SearchCharactersBusinessLogic, SearchCharactersDataStore {
    var presenter: SearchCharactersPresentationLogic?
    var repository: Repository?
    
    internal func searchCharacterNames(request: SearchCharacters.Model.Request) {
        repository = RemoteRepository()
        let nameQuery = request.characterName
        if Connectivity.isConnectedToInternet() {
            repository?.retrieveCharactersViaName(queryString: nameQuery, completion: { (results, error) in
                guard error == nil else {
                    self.presenter?.showError(with: AppError.notFoundError)
                    return
                }
                
                guard let characters = results else {
                    self.presenter?.showError(with: AppError.notFoundError)
                    return
                }
                let response = SearchCharacters.Model.Response(characters: characters)
                self.presenter?.presentSearchResults(response: response)
            })
        } else {
            self.presenter?.showError(with: AppError.noConnection)
        }
    }
    
    internal func searchAllCharacters() {
        repository = LocalRepository()
        repository?.retrieveAllCharacters(path: "characters", completion: { (characters: [Character]?, error) in
            guard error == nil else {
                self.presenter?.showError(with: AppError.resourceLoadingError)
                return
            }
            
            guard let characters = characters else {
                self.presenter?.showError(with: AppError.resourceLoadingError)
                return
            }
            let response = SearchCharacters.Model.Response(characters: characters)
            self.presenter?.presentSearchResults(response: response)
        })
    }
}

