//
//  SearchCharactersRouter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharactersRoutingLogic {
    func showCharacterDetail(with character: Character)
}

protocol SearchCharactersDataPassing {
    var dataStore: SearchCharactersDataStore? { get }
}

class SearchCharactersRouter: NSObject, SearchCharactersRoutingLogic, SearchCharactersDataPassing{
    weak var viewController: SearchCharactersViewController?
    var dataStore: SearchCharactersDataStore?
    
    func showCharacterDetail(with character: Character) {
        guard let SearchViewController = viewController else { return }
        let characterDetailVC = CharacterDetailViewController()
        characterDetailVC.character = character
        SearchViewController.show(characterDetailVC, sender: self)
    }
}
