//
//  SearchCharactersInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharactersBusinessLogic {
  func searchCharacterNames(request: SearchCharacters.Model.Request)
}

protocol SearchCharactersDataStore {
  //var name: String { get set }
}

class SearchCharactersInteractor: SearchCharactersBusinessLogic, SearchCharactersDataStore {
  var presenter: SearchCharactersPresentationLogic?
  var repository: Repository?
    
  func searchCharacterNames(request: SearchCharacters.Model.Request) {
    repository = RemoteRepository()
    
    let nameQuery = request.characterName
    repository?.retrieveCharactersViaName(queryString: nameQuery, completion: { (results: Character?, error: Error?) in
        
    })
    
   // let response = SearchCharacters.Model.Response(characters: <#[Character]#>)
   // presenter?.presentSomething(response: response)
  }
}
