//
//  SearchCharactersPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharactersPresentationLogic
{
  func presentSomething(response: SearchCharacters.Model.Response)
}

class SearchCharactersPresenter: SearchCharactersPresentationLogic
{
  weak var viewController: SearchCharactersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SearchCharacters.Model.Response)
  {
    let viewModel = SearchCharacters.Model.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
