//
//  BattleArenaInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BattleArenaBusinessLogic {
    func determineWinner(request: BattleArena.Model.Request)
}

protocol BattleArenaDataStore {
    //  var name: String { get set }
}

class BattleArenaInteractor: BattleArenaBusinessLogic, BattleArenaDataStore {
    var presenter: BattleArenaPresentationLogic?
    
    func determineWinner(request: BattleArena.Model.Request) {
        let winner = calculateWinner(fighters: request.fighters)
        let response = BattleArena.Model.Response(winner: winner)
        presenter?.presentWinner(response: response)
    }
    
    func calculateWinner(fighters: [Character]) -> Character {
        let sortedArray = fighters.sorted {(a, b) -> Bool in
            
            guard let fighterA = a.comics?.available, let fighterB = b.comics?.available else {
                return false
            }
            return fighterA > fighterB
        }
        return sortedArray.first ?? Character()
    }
}
