//
//  RankingsPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsPresentationLogic {
  func presentSomething(response: Rankings.Model.Response)
}

class RankingsPresenter: RankingsPresentationLogic {
  weak var viewController: RankingsDisplayLogic?
    
  func presentSomething(response: Rankings.Model.Response) {
    let viewModel = Rankings.Model.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
