//
//  RankingsInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsBusinessLogic {
    func doSomething(request: Rankings.Model.Request)
}

protocol RankingsDataStore {
}

class RankingsInteractor: RankingsBusinessLogic, RankingsDataStore {
    var presenter: RankingsPresentationLogic?

    func doSomething(request: Rankings.Model.Request) {
        
        
        let response = Rankings.Model.Response()
        presenter?.presentSomething(response: response)
    }
}
