//
//  RankingsInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsBusinessLogic
{
  func doSomething(request: Rankings.Something.Request)
}

protocol RankingsDataStore
{
  //var name: String { get set }
}

class RankingsInteractor: RankingsBusinessLogic, RankingsDataStore
{
  var presenter: RankingsPresentationLogic?
  var worker: RankingsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Rankings.Something.Request)
  {
    worker = RankingsWorker()
    worker?.doSomeWork()
    
    let response = Rankings.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
