//
//  RankingsViewController.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsDisplayLogic: class {
  func displaySomething(viewModel: Rankings.Model.ViewModel)
}

class RankingsViewController: UIViewController, RankingsDisplayLogic {
  var interactor: RankingsBusinessLogic?
  var router: (NSObjectProtocol & RankingsRoutingLogic & RankingsDataPassing)?

  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
    
  private func setup() {
    let viewController = self
    let interactor = RankingsInteractor()
    let presenter = RankingsPresenter()
    let router = RankingsRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
    
  override func viewDidLoad() {
    super.viewDidLoad()
    doSomething()
  }
  
  func doSomething() {
    let request = Rankings.Model.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Rankings.Model.ViewModel) {
  }
    
}
