//
//  RankingsPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RankingsPresentationLogic
{
  func presentSomething(response: Rankings.Something.Response)
}

class RankingsPresenter: RankingsPresentationLogic
{
  weak var viewController: RankingsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Rankings.Something.Response)
  {
    let viewModel = Rankings.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
