//
//  BattleArenaModels.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BattleArena {
    
    enum Model {
        struct Request {
            var fighters: [Character]
        }
        struct Response {
            var winner: Character
        }
        struct ViewModel {
            var winner: Character
        }
    }
}
