//
//  BattleArenaInteractor.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BattleArenaBusinessLogic
{
  func doSomething(request: BattleArena.Something.Request)
}

protocol BattleArenaDataStore
{
  //var name: String { get set }
}

class BattleArenaInteractor: BattleArenaBusinessLogic, BattleArenaDataStore
{
  var presenter: BattleArenaPresentationLogic?
  var worker: BattleArenaWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BattleArena.Something.Request)
  {
    worker = BattleArenaWorker()
    worker?.doSomeWork()
    
    let response = BattleArena.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
