//
//  BattleArenaPresenter.swift
//  BQMarvelBattle
//
//  Created by Tarsha de Souza on 9/5/20.
//  Copyright (c) 2020 Tarsha de Souza. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BattleArenaPresentationLogic {
    func presentWinner(response: BattleArena.Model.Response)
}

class BattleArenaPresenter: BattleArenaPresentationLogic {
    weak var viewController: BattleArenaDisplayLogic?
    
    func presentWinner(response: BattleArena.Model.Response) {
        let viewModel = BattleArena.Model.ViewModel(winner: response.winner)
        viewController?.showWinner(viewModel: viewModel)
    }
}
